FROM python:3.11.9-slim

WORKDIR /app
COPY . .

RUN apt-get update && apt-get install -y gcc && apt-get clean
RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "9004"]
