nats:
  server_url: "nats://localhost:4222"
  stream_name: "AGENT_AI_PIPELINE"
  subjects:
    input: "agentAI.input"
    analysis: "agentAI.analysis"
    output: "agentAI.output"

llm:
  api_base: "http://localhost:8000/v1"
  api_key: "dummy_key"
  model: "Qwen/Qwen3-32B"
  temperature: 0.1
  max_tokens: 2048

webapp:
  host: "0.0.0.0"
  port: 5000
  debug: true

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"